# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "functions.baml": "// Judge Conversation Quality\n// Evaluates AI coding assistant conversations for training data quality\n\nfunction JudgeConversation(conversation: string) -> ConversationScore {\n  client OpenRouterClient\n\n  prompt #\"\n    Evaluate this AI coding assistant conversation. Rate 1-5 for each criterion.\n\n    Conversation:\n    ---\n    {{ conversation }}\n    ---\n\n    Criteria:\n    - task_completion: Did assistant complete the request? (1=failed, 5=perfect)\n    - tool_use: Were tools used effectively? (1=poor, 5=excellent)\n    - response_quality: Were responses clear and helpful? (1=poor, 5=excellent)\n    - code_quality: Was code correct? (1=poor, 5=excellent, 3=no code)\n\n    Provide scores and a brief reasoning explaining your evaluation.\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
    "generators.baml": "// LLM Client Configuration\n// This defines how BAML connects to the OpenRouter API\n// Model and API key are read from environment variables set by config/scoring.yaml\n\nclient<llm> OpenRouterClient {\n  provider openai\n  options {\n    model env.OPENROUTER_MODEL\n    api_key env.OPENROUTER_API_KEY\n    base_url env.OPENROUTER_BASE_URL\n    headers {\n      \"HTTP-Referer\" env.OPENROUTER_SITE_URL\n      \"X-Title\" env.OPENROUTER_APP_NAME\n    }\n    temperature 0.1\n    max_tokens 500\n  }\n}\n",
    "types.baml": "// Conversation Quality Score\n// Structured output from LLM judge evaluation\n\nclass ConversationScore {\n  task_completion int @description(\"Did assistant complete the request? (1=failed, 5=perfect)\")\n  tool_use int @description(\"Were tools used effectively? (1=poor, 5=excellent)\")\n  response_quality int @description(\"Were responses clear and helpful? (1=poor, 5=excellent)\")\n  code_quality int @description(\"Was code correct? (1=poor, 5=excellent, 3=no code)\")\n  reasoning string @description(\"Brief explanation of the scores\")\n}\n",
}

def get_baml_files():
    return _file_map