# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (1)
# #########################################################################

class ConversationScore(BaseModel):
    task_completion: typing.Optional[int] = None
    tool_use: typing.Optional[int] = None
    response_quality: typing.Optional[int] = None
    code_quality: typing.Optional[int] = None
    reasoning: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
